# Generated by Django 3.1.1 on 2020-09-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='coordinates',
        ),
    ]
