# Generated by Django 3.1.1 on 2020-09-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='img_url',
            new_name='icon',
        ),
    ]
