# Generated by Django 3.1.1 on 2020-09-11 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_weather_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinates',
            options={'verbose_name_plural': 'Coordinates'},
        ),
        migrations.AddField(
            model_name='weather',
            name='coordinates',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.coordinates'),
            preserve_default=False,
        ),
    ]
