# Generated by Django 3.1.1 on 2020-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200911_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='weather',
            name='lat',
            field=models.FloatField(default=321.33),
        ),
        migrations.AddField(
            model_name='weather',
            name='lon',
            field=models.FloatField(default=321.33),
        ),
    ]
