# Generated by Django 3.1.1 on 2020-09-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200912_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='country',
            field=models.CharField(default='PH', max_length=100),
            preserve_default=False,
        ),
    ]
